prefs:
  network.proxy.type: 1
  network.proxy.socks_version: 5
  network.proxy.socks_remote_dns: true
  permissions.default.image: 1
  browser.display.show_image_placeholders: true
  browser.cache.disk.enable: true
  browser.cache.memory.enable: false
  browser.cache.disk.capacity: 1000000000
  media.peerconnection.enabled: false
  browser.cache.disk_cache_ssl: true
  signon.formlessCapture.enabled: true
  signon.storeWhenAutocompleteOff: true
  dom.event.contextmenu.enabled: true
  layout.css.visited_links_enabled: true
  security.ssl3.ecdhe_rsa_aes_128_sha: true
  security.ssl3.ecdhe_ecdsa_aes_128_sha: true
  security.ssl3.dhe_rsa_aes_128_sha: true
  security.ssl3.rsa_des_ede3_sha: true
  security.ssl3.dhe_rsa_aes_256_sha: true
  media.gmp-provider.enabled: false
  webgl.disabled: true
  pdfjs.enableWebGL: false
  privacy.clearOnShutdown.cache: true
  privacy.clearOnShutdown.downloads: true
  privacy.clearOnShutdown.formdata: true
  privacy.clearOnShutdown.history: true
  privacy.clearOnShutdown.offlineApps: true
  privacy.clearOnShutdown.passwords: true
  privacy.clearOnShutdown.sessions: true
  privacy.clearOnShutdown.siteSettings: true

  # network.proxy.socks:  "127.0.0.1"
  # network.proxy.socks_port:  9050
  # browser.send_pings.require_same_host: true
  # security.csp.experimentalEnabled: true
  # network.http.referer.spoofSource: true
  # security.OCSP.require: true
  # security.ssl.require_safe_negotiation: true
  # privacy.resistFingerprinting: true
  # security.mixed_content.block_active_content: true
  # security.mixed_content.block_display_content: true
  # javascript.enabled: false
  # webgl.min_capability_mode: true
  # webgl.disable-extensions: true
  # browser.display.use_document_fonts: 0
  # media.autoplay.default: 5
  # layers.acceleration.disabled: true
  # media.peerconnection.enabled: false
  # dom.battery.enabled: false
  # dom.gamepad.enabled: false
  # media.webspeech.synth.enabled: false
  # dom.w3c_touch_events.enabled: 0
  # dom.event.clipboardevents.enabled: false
  # dom.webnotifications.enabled: false
  # network.prefetch-next: false
  # network.dns.disablePrefetch: true
  # network.http.speculative-parallel-limit: 0
  # browser.formfill.enable: false
  # browser.download.folderList: 2
  # webgl.enable-webgl2: false

  # javascript.enabled: true
  # webgl.disabled: false
  # webgl.min_capability_mode: false
  # webgl.disable-extensions: false
  # layers.acceleration.disabled: false
  # media.peerconnection.enabled: true
  # media.autoplay.default: 0
  # dom.w3c_touch_events.enabled: 1
  # dom.event.clipboardevents.enabled: true
  # dom.webnotifications.enabled: true
  # network.prefetch-next: true
  # network.dns.disablePrefetch: false
  # network.http.speculative-parallel-limit: 6
  # browser.formfill.enable: true
  # browser.download.folderList: 1
  # webgl.enable-webgl2: true
  # dom.battery.enabled: true
  # dom.gamepad.enabled: true
  # media.webspeech.synth.enabled: true
